# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Tester' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tester
  pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
  pod 'GTMOAuth2', '~> 1.1.0'

  target 'TesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
