source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target ‘CalendarViewApp’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalendarViewApp
  pod 'Alamofire', '~> 4.2.0’
  pod 'Gloss', '~> 1.1.1'
  pod 'SwiftyJSON'
  pod 'SwiftDate', '~> 4.0'

  target ‘CalendarViewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
